# Generated by Django 4.2.6 on 2023-11-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaid', models.AutoField(primary_key=True, serialize=False)),
                ('countryid', models.PositiveIntegerField()),
                ('chn_name', models.CharField(max_length=64)),
                ('eng_name', models.CharField(blank=True, max_length=64, null=True)),
                ('sort', models.PositiveIntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryid', models.AutoField(primary_key=True, serialize=False)),
                ('chn_name', models.CharField(max_length=64)),
                ('eng_name', models.CharField(blank=True, max_length=64, null=True)),
                ('country_logo', models.CharField(blank=True, max_length=120, null=True)),
                ('sort', models.PositiveIntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('provinceid', models.AutoField(primary_key=True, serialize=False)),
                ('areaid', models.PositiveIntegerField(blank=True, null=True)),
                ('chn_name', models.CharField(max_length=64)),
                ('eng_name', models.CharField(blank=True, max_length=64, null=True)),
                ('sort', models.PositiveIntegerField()),
                ('countryid', models.ForeignKey(db_column='countryid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='running.country')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('areaid', models.PositiveIntegerField(blank=True, null=True)),
                ('chn_name', models.CharField(max_length=64)),
                ('eng_name', models.CharField(blank=True, max_length=64, null=True)),
                ('sort', models.PositiveIntegerField()),
                ('countryid', models.ForeignKey(db_column='countryid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='running.country')),
                ('provinceid', models.ForeignKey(db_column='provinceid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='running.province')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
